Repository DEFRA/sroc-service-team, pull requests merged in 2021-03, with the labels that each got.

#52 Update V2 Open API spec to match v0.4.0 changes
  openapi/version_2/paths/v2/billruns/invoices/invoice.yml
  openapi/versions/draft_v2.yml
Labels: documentation

#53 Add missing DELETE bill run to V2 Open API spec
  openapi/version_2/paths/v2/billruns/bill_run.yml
  openapi/versions/draft_v2.yml
Labels: documentation

#55 Update v2 docs with customer-changes endpoint
  openapi/version_2/paths/v2/customer_changes/customer_changes.yml
  openapi/versions/draft_v2.yml
Labels: enhancement

#57 Update v2 docs with DELETE bill-runs endpoint
  openapi/version_2/paths/v2/billruns/bill_run.yml
  openapi/versions/draft_v2.yml
Labels: documentation

#56 Update Open API spec for V2 /send endpoint
  openapi/version_2/openapi.yml
  openapi/version_2/paths/v2/billruns/bill_run_send.yml
Labels: documentation

#58 Remove counts from V2 view bill run Open API spec
  openapi/version_2/openapi.yml
  openapi/version_2/paths/v2/billruns/bill_run.yml
  openapi/versions/draft_v2.yml
Labels: documentation

#59 Update V2 Open API spec with latest changes
  openapi/version_2/paths/v2/billruns/bill_run.yml
  openapi/version_2/paths/v2/billruns/bill_run_status.yml
  openapi/version_2/paths/v2/billruns/invoices/invoice.yml
  openapi/versions/draft_v2.yml
Labels: documentation, housekeeping

#60 Update CMA V2 Open API spec with latest changes
  openapi/version_2/paths/v2/billruns/bill_run.yml
  openapi/version_2/paths/v2/billruns/invoices/invoice.yml
  openapi/versions/draft_v2.yml
Labels: documentation, housekeeping
