Repository DEFRA/sroc-service-team, pull requests merged in 2021-09, with the labels that each got.

#97 Add Open API doc for v0.13.1 of CHA
  openapi/versions/v0-13-1.yml
Labels: documentation

#98 Fix CHA OpenAPI spec test customer files endpoint
  openapi/openapi.yml
  openapi/versions/draft.yml
Labels: bug, documentation

#99 Add Open API doc for v0.13.2 of CHA
  openapi/versions/v0-13-2.yml
Labels: documentation

#100 Add Open API doc for v0.13.3 of CHA
  openapi/versions/v0-13-3.yml
Labels: documentation

#101 Add TCM RfC example to docs
  rfc/tcm.md
Labels: documentation

#102 Document list customer files endpoint
  openapi/openapi.yml
  openapi/paths/v2/bill_runs/licences/licence.yml
  openapi/paths/v2/customer_files/customer_files.yml
  openapi/schema/fields.yml
  openapi/schema/parameters.yml
  openapi/schema/schemas.yml
  openapi/versions/draft.yml
Labels: documentation

#104 Fix Customer Files endpoint ID's
  openapi/paths/admin/test/customers.yml
  openapi/versions/draft.yml
Labels: bug

#105 Fix invalid value for customer files 'required'
  openapi/schema/parameters.yml
  openapi/versions/draft.yml
Labels: bug

#103 Update admin generate bill run OpenAPI details
  openapi/paths/admin/test/bill_runs.yml
  openapi/versions/draft.yml
Labels: documentation

#106 Add Open API doc for v0.14.0 of CHA
  openapi/versions/v0-14-0.yml
Labels: documentation
